name: Publish canary
on:
  push:
    branches:
      - "canary"

env:
  NPM_TOKEN: ""

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Test
        uses: borales/actions-yarn@v4
        with:
          cmd: git-hook-tasks pre-push
      - name: Publish Canary
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
        run: ./scripts/publish-canary.sh
